Repository ka8540/SWEN732-team1, pull requests merged in 2024-04, with the labels that each got.

#15 Homepage categories ka8540
  .DS_Store
  .github/workflows/python-app.yml
  .gitignore
  PCP/.DS_Store
  PCP/App.js
  PCP/Home.js
  PCP/Phones.js
  PCP/Retailer.js
  PCP/server/src/model/amazon.py
  PCP/server/src/utilities/swen_344_db_utils.py
Labels: enhancement

#17 added the search bar function inside the home page
  PCP/Home.js
  PCP/package-lock.json
  PCP/package.json
Labels: enhancement

#36 Fix issues
  PCP/server/data/data.sql
  PCP/server/src/api/login_api.py
  PCP/server/src/utilities/swen_344_db_utils.py
  PCP/server/tests/1_api/test_1_signup_api.py
  PCP/server/tests/1_api/test_2_login_api.py
  PCP/server/tests/1_api/test_3_logout_api.py
  PCP/server/tests/1_api/test_4_user_detail_api.py
  PCP/server/tests/1_api/test_5_categories_api.py
  PCP/server/tests/2_db/test_1_signup_db.py
  PCP/server/tests/2_db/test_3_logout_db.py
  PCP/server/tests/2_db/test_4_user_detail_db.py
  PCP/server/tests/2_db/test_5_categories_db.py
  PCP/server/tests/2_db/test_6_products_db.py
  PCP/server/tests/2_db/test_7_price_db.py
Labels: issue fixed

#38 edit Fav and Cart
  PCP/Home.js
  PCP/Retailer.js
  PCP/ShoppingCart.js
  PCP/server/.DS_Store
  PCP/server/data/Amazon.xlsx
  PCP/server/src/.DS_Store
  images/10M.jpeg
  images/11M.jpeg
  images/1M.jpeg
  images/2M.jpeg
  images/3M.jpeg
  images/4M.jpeg
  images/5M.jpeg
  images/6M.png
  images/7M.webp
  images/8M.jpeg
  images/9M.png
Labels: enhancement

#37 cart api done
  PCP/server/data/data.sql
  PCP/server/src/api/cart_api.py
  PCP/server/src/api/user_favorites_api.py
  PCP/server/src/db/cart.py
  PCP/server/src/server.py
Labels: enhancement

#39 Best buy la3679
  PCP/server/data/data.sql
  PCP/server/src/api/cart_api.py
  PCP/server/src/api/price_conversion_api.py
  PCP/server/src/db/price_conversion.py
  PCP/server/src/model/bestbut.py
  PCP/server/src/server.py
Labels: enhancement

#40 Fav cart ka8540
  PCP/Favourite.js
  PCP/Retailer.js
  PCP/ShoppingCart.js
  PCP/server/data/data.sql
  PCP/server/src/api/cart_api.py
  PCP/server/src/api/user_favorites_api.py
  PCP/server/src/db/user_favorites.py
  PCP/server/src/server.py
  package-lock.json
  package.json
Labels: documentation, enhancement

#45 added the currency change api and added the button for it and changes…
  PCP/Retailer.js
  PCP/package-lock.json
  PCP/package.json
  PCP/server/src/api/price_conversion_api.py
  PCP/server/src/db/price_conversion.py
  package-lock.json
  package.json
Labels: enhancement

#46 edit ShoppingCart API and .JS file
  PCP/App.js
  PCP/Favourite.js
  PCP/Home.js
  PCP/Login.js
  PCP/ShoppingCart.js
  PCP/package-lock.json
  PCP/server/src/api/cart_api.py
  PCP/server/src/db/cart.py
Labels: enhancement

#47 edit Readme.md file
  DesignDoc.md
  images/Cart.png
  images/CartUpdateQuantity.png
  images/FavRemove.png
  images/Favourite.png
  images/Home_Page_2.png
  images/Login copy.png
  images/ProductDescription_2y.png
  images/Products_2.png
  images/Retailers.png
Labels: documentation
